/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tgs13.bingo;

import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class telaBingo extends javax.swing.JFrame {
    
    private int sel;
    private int bingo[];
    private int random = 0;
    private boolean test = false;
    private String sele;
    private DefaultListModel listaSorteados = new DefaultListModel();
    private DefaultListModel listaFaltaSortear = new DefaultListModel();
    private int ordemSorteados = 1;
    
    

    /**
     * Creates new form telaBingo
     */
    
    public telaBingo() {
        initComponents();
        
        do {
        
        sele = JOptionPane.showInputDialog("Digite quantos numeros você quer no bingo: [75] ou [90]");
        sel = Integer.parseInt(sele);
        
        } while (sel != 75 && sel != 90);
        
        bingo = OperacoesBingo.SetArrayLenght(bingo, sel);
        
        Arrays.fill(bingo, 0);
        listaFaltaSortear = OperacoesBingo.FillList(listaFaltaSortear, bingo);
        faltaSortear.setModel(listaFaltaSortear);
        
        
    }
    
    
                   
    
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        abaSorteados = new javax.swing.JScrollPane();
        sorteados = new javax.swing.JList<>();
        abaFaltaSortear = new javax.swing.JScrollPane();
        faltaSortear = new javax.swing.JList<>();
        botaoSortear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nSort = new javax.swing.JLabel();
        labelNumeroSorteado = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel4.setText("Total Sorteados:");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(263, 158));

        abaSorteados.setAutoscrolls(true);
        abaSorteados.setMaximumSize(new java.awt.Dimension(263, 158));

        sorteados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sorteados.setForeground(new java.awt.Color(0, 0, 255));
        sorteados.setVisibleRowCount(1);
        sorteados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sorteadosMouseClicked(evt);
            }
        });
        abaSorteados.setViewportView(sorteados);

        jTabbedPane1.addTab("Sorteados", abaSorteados);

        faltaSortear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        faltaSortear.setForeground(new java.awt.Color(255, 0, 51));
        abaFaltaSortear.setViewportView(faltaSortear);

        jTabbedPane1.addTab("Falta Sortear", abaFaltaSortear);

        botaoSortear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaoSortear.setForeground(new java.awt.Color(255, 51, 51));
        botaoSortear.setText("SORTEAR NÚMERO");
        botaoSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSortearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BINGO");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Criador Thiago Gonçalves Souza");

        nSort.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nSort.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nSort.setText("Número Sorteado:");

        labelNumeroSorteado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNumeroSorteado.setForeground(new java.awt.Color(0, 51, 204));
        labelNumeroSorteado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumeroSorteado.setText("???");

        jButton2.setText("Resetar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoSortear, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nSort)
                    .addComponent(labelNumeroSorteado))
                .addGap(18, 18, 18)
                .addComponent(botaoSortear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSortearActionPerformed
        // TODO add your handling code here:
        
        
        
        new Thread() {
            
            @Override
            public void run() {
                
                                                     
                            if (ordemSorteados <= sel) {
                                                                                    
                            nSort.setText(String.format("[" + ordemSorteados++ + "°]" + " Número Sorteado:"));
                            
        
                            } else {
            
                            botaoSortear.setText("ACABOU O BINGO!!!");
                            
                            
            
                            }
            
                        
                            do {
            
                            random = OperacoesBingo.Aleatorio(random,sel);
                            
                            test = OperacoesBingo.TestarIgual(test, bingo, random);
            
            
                             } while ( (test == true) || (random == 0) ); 
                        
                            if (ordemSorteados <= sel + 1) {
        
                            labelNumeroSorteado.setText(Integer.toString(random));
        
                            } else {
           
                            labelNumeroSorteado.setText("X");
            
                            }
                        
                            bingo = OperacoesBingo.AdicionarAoVetor(bingo, random);
                        
                            listaSorteados = OperacoesBingo.AdicionarElementosLista(listaSorteados, bingo);
        
                            sorteados.setModel(listaSorteados);
        
        
        
                            listaFaltaSortear = OperacoesBingo.FaltaSortear(listaFaltaSortear, bingo, random);
        
                            faltaSortear.setModel(listaFaltaSortear);
                
            }
            
            
            
        }.start();
        
        
       
        
        
        
        
        
        
        
        
       
        
    }//GEN-LAST:event_botaoSortearActionPerformed

    private void sorteadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sorteadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sorteadosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
            // TODO add your handling code here:
        
            
        random = 0;
        test = false;
        sele = "0";
        listaSorteados.removeAllElements();
        sorteados.setModel(listaSorteados);
        listaFaltaSortear.removeAllElements();
        ordemSorteados = 1;
        
        nSort.setText("Número Sorteado");
        labelNumeroSorteado.setText("???");
        botaoSortear.setText("SORTEAR NÚMERO");
        
            
        
        do {
        
        sele = JOptionPane.showInputDialog("Digite quantos numeros você quer no bingo: [75] ou [90]");
        sel = Integer.parseInt(sele);
        
        } while (sel != 75 && sel != 90);
        
        bingo = OperacoesBingo.SetArrayLenght(bingo, sel);
        
        Arrays.fill(bingo, 0);
        listaFaltaSortear = OperacoesBingo.FillList(listaFaltaSortear, bingo);
        faltaSortear.setModel(listaFaltaSortear);
        listaSorteados.removeAllElements();
        sorteados.setModel(listaSorteados);
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaBingo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane abaFaltaSortear;
    private javax.swing.JScrollPane abaSorteados;
    private javax.swing.JButton botaoSortear;
    private javax.swing.JList<String> faltaSortear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelNumeroSorteado;
    private javax.swing.JLabel nSort;
    private javax.swing.JList<String> sorteados;
    // End of variables declaration//GEN-END:variables
}
